"""
TESTS is a dict with all you tests.
Keys for this will be categories' names.
Each test is dict with
    "input" -- input data for user function
    "answer" -- your right answer
    "explanation" -- not necessary key, it's using for additional info in animation.
"""

TESTS = {
    "Basics": [
        {
            "input": ['oruoreemdstmioitlpslam', 4123],
            "answer": "loremipsumdolorsitamet",
            "explanation": [['l', 'or', 'e', 'mi'], ['ps', 'u', 'md', 'o'], ['l', 'or', 's', 'it'], ['am', 'e', 't']]
        },
        {
            "input": ['kicheco', 23415],
            "answer": "checkio",
            "explanation": [['c', 'he', 'c', 'ki', 'o']]
        },
        {
            "input": ['hrewhoorrowyilmmmoaouletow', 123],
            "answer": "howareyouwillhometommorrow",
            "explanation": [['h', 'ow', 'a'], ['re', 'y', 'ou'], ['w', 'il', 'l'], ['ho', 'm', 'et'], ['o', 'mm', 'o'],
                            ['rr', 'o', 'w']]
        },
    ],
    "Extra": [
        {
            "input": ['lsesanaeamiauelodosadonpieulneittgemtdsorstenomemalorccicegnsutadalirpmeritolomcoiengae',
                      654287931],
            "answer": "loremipsumdolorsitametconsectetueradipiscingelitaeneancommodoligulaegetdoloraeneanmassa",
            "explanation": [['l', 'or', 'e', 'mi', 'p', 'su', 'm', 'do', 'l'],
                            ['or', 's', 'it', 'a', 'me', 't', 'co', 'n', 'se'],
                            ['c', 'te', 't', 'ue', 'r', 'ad', 'i', 'pi', 's'],
                            ['ci', 'n', 'ge', 'l', 'it', 'a', 'en', 'e', 'an'],
                            ['c', 'om', 'm', 'od', 'o', 'li', 'g', 'ul', 'a'],
                            ['eg', 'e', 'td', 'o', 'lo', 'r', 'ae', 'n', 'ea'], ['n', 'ma', 's', 'sa']]
        },
        {
            "input": [
                'fuynpnireeesgwowhiancxitwhethsemheaodiiseaisttmieiogarepmettasaanhovythodtaikeeonfoydbrsstsawoeassfmoheofscwiemaeareishtelulepprbshitmqunneahoadrnkesntenertiwleyeepndmsutsuhtrareaygaeitdenaksenlesiriehmaontofeposfoslimmynrbxseeletlenldbwietttndtertttehelswreaistufamblosaweannerriteiotikwngnnjyrteheeintcrrofksoddsequntrxhactsblensthmoyhawerhnwlleiarndirppcpeefmnstmtoryalshosoesttmohiyoladfhsthicaeboinarfantsofnteiytsncfsioreeifiagrnoieltvauhenesrftelitutatehncnretesyulsrnphithelelmncswadissiayieoeeeericegleupaaglaenaelveaswhtvamoumernhereiageefellinua',
                526341],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n', 'de', 'r', 'fu'], ['ls', 'e', 're', 'n', 'it', 'y'],
                            ['h', 'as', 't', 'ak', 'e', 'np'], ['os', 's', 'es', 's', 'io', 'n'],
                            ['o', 'fm', 'y', 'en', 't', 'ir'], ['es', 'o', 'ul', 'l', 'ik', 'e'],
                            ['t', 'he', 's', 'es', 'w', 'ee'], ['tm', 'o', 'rn', 'i', 'ng', 's'],
                            ['o', 'fs', 'p', 'ri', 'n', 'gw'], ['hi', 'c', 'hi', 'e', 'nj', 'o'],
                            ['y', 'wi', 't', 'hm', 'y', 'wh'], ['ol', 'e', 'he', 'a', 'rt', 'i'],
                            ['a', 'ma', 'l', 'on', 'e', 'an'], ['df', 'e', 'el', 't', 'he', 'c'],
                            ['h', 'ar', 'm', 'of', 'e', 'xi'], ['st', 'e', 'nc', 'e', 'in', 't'],
                            ['h', 'is', 's', 'po', 't', 'wh'], ['ic', 'h', 'wa', 's', 'cr', 'e'],
                            ['a', 'te', 'd', 'fo', 'r', 'th'], ['eb', 'l', 'is', 's', 'of', 's'],
                            ['o', 'ul', 's', 'li', 'k', 'em'], ['in', 'e', 'ia', 'm', 'so', 'h'],
                            ['a', 'pp', 'y', 'my', 'd', 'ea'], ['rf', 'r', 'ie', 'n', 'ds', 'o'],
                            ['a', 'bs', 'o', 'rb', 'e', 'di'], ['nt', 'h', 'ee', 'x', 'qu', 'i'],
                            ['s', 'it', 'e', 'se', 'n', 'se'], ['of', 'm', 'er', 'e', 'tr', 'a'],
                            ['n', 'qu', 'i', 'le', 'x', 'is'], ['te', 'n', 'ce', 't', 'ha', 't'],
                            ['i', 'ne', 'g', 'le', 'c', 'tm'], ['yt', 'a', 'le', 'n', 'ts', 'i'],
                            ['s', 'ho', 'u', 'ld', 'b', 'ei'], ['nc', 'a', 'pa', 'b', 'le', 'o'],
                            ['f', 'dr', 'a', 'wi', 'n', 'ga'], ['si', 'n', 'gl', 'e', 'st', 'r'],
                            ['o', 'ke', 'a', 'tt', 'h', 'ep'], ['re', 's', 'en', 't', 'mo', 'm'],
                            ['e', 'nt', 'a', 'nd', 'y', 'et'], ['if', 'e', 'el', 't', 'ha', 't'],
                            ['i', 'ne', 'v', 'er', 'w', 'as'], ['ag', 'r', 'ea', 't', 'er', 'a'],
                            ['r', 'ti', 's', 'tt', 'h', 'an'], ['no', 'w', 'wh', 'e', 'nw', 'h'],
                            ['i', 'le', 't', 'he', 'l', 'ov'], ['el', 'y', 'va', 'l', 'le', 'y'],
                            ['t', 'ee', 'm', 'sw', 'i', 'th'], ['va', 'p', 'ou', 'r', 'ar', 'o'],
                            ['u', 'nd', 'm', 'ea', 'n', 'dt'], ['he', 'm', 'er', 'i', 'di', 'a'],
                            ['n', 'su', 'n', 'st', 'r', 'ik'], ['es', 't', 'he', 'u', 'pp', 'e'],
                            ['r', 'su', 'r', 'fa', 'c', 'eo'], ['ft', 'h', 'ei', 'm', 'pe', 'n'],
                            ['e', 'tr', 'a', 'bl', 'e', 'fo'], ['li', 'a', 'ge', 'o', 'fm', 'y'],
                            ['t', 're', 'e', 'sa', 'n', 'db'], ['ut', 'a', 'fe', 'w', 'st', 'r'],
                            ['a', 'yg', 'l', 'ea', 'm', 'ss'], ['te', 'a', 'li', 'n', 'to', 't'],
                            ['h', 'ei', 'n', 'ne', 'r', 'sa'], ['nc', 't', 'ua', 'r', 'y']]
        },
        {
            "input": ['cmpduiuzyowerovkbsogqxjaheoaltnfr', 87621543],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui', 'c', 'kb', 'r', 'ow'], ['nf', 'o', 'xj', 'u', 'mp', 's', 'ov', 'e'],
                            ['r', 'al', 'a', 'zy', 'd', 'og']]
        },
        {
            "input": [
                'ntyeirsgshwhlecnwhdfsieaouieisgsipgaaomeasswhvthmiaheoamyfssnfutonueepjohanmntwthsohidieractmueogepaateanteyodtnpeefoetrlsawoissthenicymahtetteonedbsqfmxnetcankemfewtinlyinddstctrftameiydehsseesoieoonhceifooamrrbsretlesabstteltattialveaneufbltewtnelakolltriyeadofhaseliaennsenetyldflerndiatnheturhstrimlsaainnrnpykergwttiexisreiemysoeseiatleiatreetvrawovmroeikrengdbloturasisowfsnleearichrulsfreittencholinhnthgrhlelapnsuptheresearaenoentnihhmaltspoassimyaexoleiennwiontierrheeswuriefaeeoueaharseefmimonwirfeeiscblkppdthnquhtabdrsesyneeowleeaemrsupianygtct',
                831472596],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n', 'de', 'r', 'fu', 'l', 'se', 'r'],
                            ['en', 'i', 'ty', 'h', 'as', 't', 'ak', 'e', 'np'],
                            ['o', 'ss', 'e', 'ss', 'i', 'on', 'o', 'fm', 'y'],
                            ['en', 't', 'ir', 'e', 'so', 'u', 'll', 'i', 'ke'],
                            ['t', 'he', 's', 'es', 'w', 'ee', 't', 'mo', 'r'],
                            ['ni', 'n', 'gs', 'o', 'fs', 'p', 'ri', 'n', 'gw'],
                            ['h', 'ic', 'h', 'ie', 'n', 'jo', 'y', 'wi', 't'],
                            ['hm', 'y', 'wh', 'o', 'le', 'h', 'ea', 'r', 'ti'],
                            ['a', 'ma', 'l', 'on', 'e', 'an', 'd', 'fe', 'e'],
                            ['lt', 'h', 'ec', 'h', 'ar', 'm', 'of', 'e', 'xi'],
                            ['s', 'te', 'n', 'ce', 'i', 'nt', 'h', 'is', 's'],
                            ['po', 't', 'wh', 'i', 'ch', 'w', 'as', 'c', 're'],
                            ['a', 'te', 'd', 'fo', 'r', 'th', 'e', 'bl', 'i'],
                            ['ss', 'o', 'fs', 'o', 'ul', 's', 'li', 'k', 'em'],
                            ['i', 'ne', 'i', 'am', 's', 'oh', 'a', 'pp', 'y'],
                            ['my', 'd', 'ea', 'r', 'fr', 'i', 'en', 'd', 'so'],
                            ['a', 'bs', 'o', 'rb', 'e', 'di', 'n', 'th', 'e'],
                            ['ex', 'q', 'ui', 's', 'it', 'e', 'se', 'n', 'se'],
                            ['o', 'fm', 'e', 're', 't', 'ra', 'n', 'qu', 'i'],
                            ['le', 'x', 'is', 't', 'en', 'c', 'et', 'h', 'at'],
                            ['i', 'ne', 'g', 'le', 'c', 'tm', 'y', 'ta', 'l'],
                            ['en', 't', 'si', 's', 'ho', 'u', 'ld', 'b', 'ei'],
                            ['n', 'ca', 'p', 'ab', 'l', 'eo', 'f', 'dr', 'a'],
                            ['wi', 'n', 'ga', 's', 'in', 'g', 'le', 's', 'tr'],
                            ['o', 'ke', 'a', 'tt', 'h', 'ep', 'r', 'es', 'e'],
                            ['nt', 'm', 'om', 'e', 'nt', 'a', 'nd', 'y', 'et'],
                            ['i', 'fe', 'e', 'lt', 'h', 'at', 'i', 'ne', 'v'],
                            ['er', 'w', 'as', 'a', 'gr', 'e', 'at', 'e', 'ra'],
                            ['r', 'ti', 's', 'tt', 'h', 'an', 'n', 'ow', 'w'],
                            ['he', 'n', 'wh', 'i', 'le', 't', 'he', 'l', 'ov'],
                            ['e', 'ly', 'v', 'al', 'l', 'ey', 't', 'ee', 'm'],
                            ['sw', 'i', 'th', 'v', 'ap', 'o', 'ur', 'a', 'ro'],
                            ['u', 'nd', 'm', 'ea', 'n', 'dt', 'h', 'em', 'e'],
                            ['ri', 'd', 'ia', 'n', 'su', 'n', 'st', 'r', 'ik'],
                            ['e', 'st', 'h', 'eu', 'p', 'pe', 'r', 'su', 'r'],
                            ['fa', 'c', 'eo', 'f', 'th', 'e', 'im', 'p', 'en'],
                            ['e', 'tr', 'a', 'bl', 'e', 'fo', 'l', 'ia', 'g'],
                            ['eo', 'f', 'my', 't', 're', 'e', 'sa', 'n', 'db'],
                            ['u', 'ta', 'f', 'ew', 's', 'tr', 'a', 'yg', 'l'],
                            ['ea', 'm', 'ss', 't', 'ea', 'l', 'in', 't', 'ot'],
                            ['h', 'ei', 'n', 'ne', 'r', 'sa', 'n', 'ct', 'u'], ['ar', 'y']]
        },
        {
            "input": [
                'itohdeindiiwaoutdtagrrhedpprkelfbpechowealrstenoeloeoofsetsiuurlroerebailenureganyacsoulthothunhosldsetutsoweionncxfuswhresicanccioctansasplaakosunrneteexpaoflrubmaodiiitieboknuatuueeinineuirabeieoceshncmlemuyisangpnwiconemhcheofmeriejseaeleaodtaslcohmerrevsobitibeomsiancgrutnltincapadoucysnteeretilaneisplisbewhplnteetrlthosutnoubuarccoipomusoumofpraallmtoaeaiattasoneeorscaausoopuyenatlagaesrtasticnatnwdurexowtenasioivethetusxpterusnsvoeserthtrsrcoqreainorpsnpfpaslycicihiptehisdleisbgplfndcngehetfhsctaurusuenourenseaypanyodeielsaulanhpaeat',
                25146873],
            "answer": "butimustexplaintoyouhowallthismistakenideaofdenouncingpleasureandpraisingpainwasbornandiwillgiveyouacompleteaccountofthesystemandexpoundtheactualteachingsofthegreatexplorerofthetruththemasterbuilderofhumanhappinessnoonerejectsdislikesoravoidspleasureitselfbecauseitispleasurebutbecausethosewhodonotknowhowtopursuepleasurerationallyencounterconsequencesthatareextremelypainfulnoragainisthereanyonewholovesorpursuesordesirestoobtainpainofitselfbecauseitispainbutbecauseoccasionallycircumstancesoccurinwhichtoilandpaincanprocurehimsomegreatpleasure",
            "explanation": [['b', 'ut', 'i', 'mu', 's', 'te', 'x', 'pl'], ['ai', 'n', 'to', 'y', 'ou', 'h', 'ow', 'a'],
                            ['l', 'lt', 'h', 'is', 'm', 'is', 't', 'ak'], ['en', 'i', 'de', 'a', 'of', 'd', 'en', 'o'],
                            ['u', 'nc', 'i', 'ng', 'p', 'le', 'a', 'su'], ['re', 'a', 'nd', 'p', 'ra', 'i', 'si', 'n'],
                            ['g', 'pa', 'i', 'nw', 'a', 'sb', 'o', 'rn'], ['an', 'd', 'iw', 'i', 'll', 'g', 'iv', 'e'],
                            ['y', 'ou', 'a', 'co', 'm', 'pl', 'e', 'te'], ['ac', 'c', 'ou', 'n', 'to', 'f', 'th', 'e'],
                            ['s', 'ys', 't', 'em', 'a', 'nd', 'e', 'xp'], ['ou', 'n', 'dt', 'h', 'ea', 'c', 'tu', 'a'],
                            ['l', 'te', 'a', 'ch', 'i', 'ng', 's', 'of'], ['th', 'e', 'gr', 'e', 'at', 'e', 'xp', 'l'],
                            ['o', 're', 'r', 'of', 't', 'he', 't', 'ru'], ['th', 't', 'he', 'm', 'as', 't', 'er', 'b'],
                            ['u', 'il', 'd', 'er', 'o', 'fh', 'u', 'ma'], ['nh', 'a', 'pp', 'i', 'ne', 's', 'sn', 'o'],
                            ['o', 'ne', 'r', 'ej', 'e', 'ct', 's', 'di'], ['sl', 'i', 'ke', 's', 'or', 'a', 'vo', 'i'],
                            ['d', 'sp', 'l', 'ea', 's', 'ur', 'e', 'it'], ['se', 'l', 'fb', 'e', 'ca', 'u', 'se', 'i'],
                            ['t', 'is', 'p', 'le', 'a', 'su', 'r', 'eb'], ['ut', 'b', 'ec', 'a', 'us', 'e', 'th', 'o'],
                            ['s', 'ew', 'h', 'od', 'o', 'no', 't', 'kn'], ['ow', 'h', 'ow', 't', 'op', 'u', 'rs', 'u'],
                            ['e', 'pl', 'e', 'as', 'u', 're', 'r', 'at'], ['io', 'n', 'al', 'l', 'ye', 'n', 'co', 'u'],
                            ['n', 'te', 'r', 'co', 'n', 'se', 'q', 'ue'], ['nc', 'e', 'st', 'h', 'at', 'a', 're', 'e'],
                            ['x', 'tr', 'e', 'me', 'l', 'yp', 'a', 'in'], ['fu', 'l', 'no', 'r', 'ag', 'a', 'in', 'i'],
                            ['s', 'th', 'e', 're', 'a', 'ny', 'o', 'ne'], ['wh', 'o', 'lo', 'v', 'es', 'o', 'rp', 'u'],
                            ['r', 'su', 'e', 'so', 'r', 'de', 's', 'ir'], ['es', 't', 'oo', 'b', 'ta', 'i', 'np', 'a'],
                            ['i', 'no', 'f', 'it', 's', 'el', 'f', 'be'], ['ca', 'u', 'se', 'i', 'ti', 's', 'pa', 'i'],
                            ['n', 'bu', 't', 'be', 'c', 'au', 's', 'eo'], ['cc', 'a', 'si', 'o', 'na', 'l', 'ly', 'c'],
                            ['i', 'rc', 'u', 'ms', 't', 'an', 'c', 'es'], ['oc', 'c', 'ur', 'i', 'nw', 'h', 'ic', 'h'],
                            ['t', 'oi', 'l', 'an', 'd', 'pa', 'i', 'nc'], ['an', 'p', 'ro', 'c', 'ur', 'e', 'hi', 'm'],
                            ['s', 'om', 'e', 'gr', 'e', 'at', 'p', 'le'], ['as', 'u', 're']]
        },
        {
            "input": ['henveqforkbmzytowoogcjuauixalrpsd', 4126537],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui', 'c', 'kb', 'r'], ['ow', 'n', 'fo', 'x', 'ju', 'm', 'ps'],
                            ['o', 've', 'r', 'al', 'a', 'zy', 'd'], ['og']]
        },
        {
            "input": ['uinpsatkbxvedqowmalcfoozyherjurog', 25314],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui', 'c'], ['kb', 'r', 'ow', 'n', 'fo'], ['x', 'ju', 'm', 'ps', 'o'],
                            ['ve', 'r', 'al', 'a', 'zy'], ['d', 'og']]
        },
        {
            "input": [
                'laseenieeoicteaeecsiswfooemafroexnratnelldlgaoesaltwranlevswadtnstrimemyuyglneyneneoneherrinwhafemcetreeulimyddisfmietcsindrgttmetigrsheleyvndestpeoeiaeewmotnasetsstketfshhmranhtesasrfsippirbqsenengenbeoskeendhasrowtalirohsuhfapfottalinrdeinpososninjoomaeofiwhablsamdsonitelehtmscaalehomineettnovtapmrirpeftrgsassshctfuhssyllwgshwihonhxihchdsskohrbsesetisitauabntrrnteereanilymurniaesueblfdbaeanarworakiirtmopieytidarnpocthoneyeneuioqucleteifinantyatatiwhelthuemneucenlrefeatsartyofmuesngwylelltentiteiliseaatherexatyhopwisepefevathwheeeoeadikrthaeontrteiu',
                3624751],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n', 'de', 'r', 'fu', 'l'], ['se', 'r', 'en', 'i', 'ty', 'h', 'as'],
                            ['t', 'ak', 'e', 'np', 'o', 'ss', 'e'], ['ss', 'i', 'on', 'o', 'fm', 'y', 'en'],
                            ['t', 'ir', 'e', 'so', 'u', 'll', 'i'], ['ke', 't', 'he', 's', 'es', 'w', 'ee'],
                            ['t', 'mo', 'r', 'ni', 'n', 'gs', 'o'], ['fs', 'p', 'ri', 'n', 'gw', 'h', 'ic'],
                            ['h', 'ie', 'n', 'jo', 'y', 'wi', 't'], ['hm', 'y', 'wh', 'o', 'le', 'h', 'ea'],
                            ['r', 'ti', 'a', 'ma', 'l', 'on', 'e'], ['an', 'd', 'fe', 'e', 'lt', 'h', 'ec'],
                            ['h', 'ar', 'm', 'of', 'e', 'xi', 's'], ['te', 'n', 'ce', 'i', 'nt', 'h', 'is'],
                            ['s', 'po', 't', 'wh', 'i', 'ch', 'w'], ['as', 'c', 're', 'a', 'te', 'd', 'fo'],
                            ['r', 'th', 'e', 'bl', 'i', 'ss', 'o'], ['fs', 'o', 'ul', 's', 'li', 'k', 'em'],
                            ['i', 'ne', 'i', 'am', 's', 'oh', 'a'], ['pp', 'y', 'my', 'd', 'ea', 'r', 'fr'],
                            ['i', 'en', 'd', 'so', 'a', 'bs', 'o'], ['rb', 'e', 'di', 'n', 'th', 'e', 'ex'],
                            ['q', 'ui', 's', 'it', 'e', 'se', 'n'], ['se', 'o', 'fm', 'e', 're', 't', 'ra'],
                            ['n', 'qu', 'i', 'le', 'x', 'is', 't'], ['en', 'c', 'et', 'h', 'at', 'i', 'ne'],
                            ['g', 'le', 'c', 'tm', 'y', 'ta', 'l'], ['en', 't', 'si', 's', 'ho', 'u', 'ld'],
                            ['b', 'ei', 'n', 'ca', 'p', 'ab', 'l'], ['eo', 'f', 'dr', 'a', 'wi', 'n', 'ga'],
                            ['s', 'in', 'g', 'le', 's', 'tr', 'o'], ['ke', 'a', 'tt', 'h', 'ep', 'r', 'es'],
                            ['e', 'nt', 'm', 'om', 'e', 'nt', 'a'], ['nd', 'y', 'et', 'i', 'fe', 'e', 'lt'],
                            ['h', 'at', 'i', 'ne', 'v', 'er', 'w'], ['as', 'a', 'gr', 'e', 'at', 'e', 'ra'],
                            ['r', 'ti', 's', 'tt', 'h', 'an', 'n'], ['ow', 'w', 'he', 'n', 'wh', 'i', 'le'],
                            ['t', 'he', 'l', 'ov', 'e', 'ly', 'v'], ['al', 'l', 'ey', 't', 'ee', 'm', 'sw'],
                            ['i', 'th', 'v', 'ap', 'o', 'ur', 'a'], ['ro', 'u', 'nd', 'm', 'ea', 'n', 'dt'],
                            ['h', 'em', 'e', 'ri', 'd', 'ia', 'n'], ['su', 'n', 'st', 'r', 'ik', 'e', 'st'],
                            ['h', 'eu', 'p', 'pe', 'r', 'su', 'r'], ['fa', 'c', 'eo', 'f', 'th', 'e', 'im'],
                            ['p', 'en', 'e', 'tr', 'a', 'bl', 'e'], ['fo', 'l', 'ia', 'g', 'eo', 'f', 'my'],
                            ['t', 're', 'e', 'sa', 'n', 'db', 'u'], ['ta', 'f', 'ew', 's', 'tr', 'a', 'yg'],
                            ['l', 'ea', 'm', 'ss', 't', 'ea', 'l'], ['in', 't', 'ot', 'h', 'ei', 'n', 'ne'],
                            ['r', 'sa', 'n', 'ct', 'u', 'ar', 'y']]
        },
        {
            "input": [
                'iaiomidunaraianimposyeeaathxthhuiunerslvsuftirushowrurantqatefuianlrsstafcapcasircnwlanhearmunwaseacsuinwdvelunsxpcchepleemlmasejioirbesebeodhsuelleueamelniyovuiriituaiuioceshanpimtestoltaoinrsiaiwyettteotuigrotradensnekedeicpluthoowerayrcnrelnosoneesenpssensenumoicdrosplteyltkfdgeansbioueofmunangereustrhaoctssptauetbonotpltenoceeyprthesoostaelibuoalscchpacomeutluhsnioleppanlgoccendhteftefhtbfhineiraaelisuaewnpusonusehtrngaehoudebnoeisecacanioicrersubxpohieenpndgorlacathadtlsoaroteropposdolesseaecstkoeaiconstxaiaerwrprooifbttbclyturtinuega',
                651234],
            "answer": "butimustexplaintoyouhowallthismistakenideaofdenouncingpleasureandpraisingpainwasbornandiwillgiveyouacompleteaccountofthesystemandexpoundtheactualteachingsofthegreatexplorerofthetruththemasterbuilderofhumanhappinessnoonerejectsdislikesoravoidspleasureitselfbecauseitispleasurebutbecausethosewhodonotknowhowtopursuepleasurerationallyencounterconsequencesthatareextremelypainfulnoragainisthereanyonewholovesorpursuesordesirestoobtainpainofitselfbecauseitispainbutbecauseoccasionallycircumstancesoccurinwhichtoilandpaincanprocurehimsomegreatpleasure",
            "explanation": [['b', 'ut', 'i', 'mu', 's', 'te'], ['xp', 'l', 'ai', 'n', 'to', 'y'],
                            ['o', 'uh', 'o', 'wa', 'l', 'lt'], ['hi', 's', 'mi', 's', 'ta', 'k'],
                            ['e', 'ni', 'd', 'ea', 'o', 'fd'], ['en', 'o', 'un', 'c', 'in', 'g'],
                            ['p', 'le', 'a', 'su', 'r', 'ea'], ['nd', 'p', 'ra', 'i', 'si', 'n'],
                            ['g', 'pa', 'i', 'nw', 'a', 'sb'], ['or', 'n', 'an', 'd', 'iw', 'i'],
                            ['l', 'lg', 'i', 've', 'y', 'ou'], ['ac', 'o', 'mp', 'l', 'et', 'e'],
                            ['a', 'cc', 'o', 'un', 't', 'of'], ['th', 'e', 'sy', 's', 'te', 'm'],
                            ['a', 'nd', 'e', 'xp', 'o', 'un'], ['dt', 'h', 'ea', 'c', 'tu', 'a'],
                            ['l', 'te', 'a', 'ch', 'i', 'ng'], ['so', 'f', 'th', 'e', 'gr', 'e'],
                            ['a', 'te', 'x', 'pl', 'o', 're'], ['ro', 'f', 'th', 'e', 'tr', 'u'],
                            ['t', 'ht', 'h', 'em', 'a', 'st'], ['er', 'b', 'ui', 'l', 'de', 'r'],
                            ['o', 'fh', 'u', 'ma', 'n', 'ha'], ['pp', 'i', 'ne', 's', 'sn', 'o'],
                            ['o', 'ne', 'r', 'ej', 'e', 'ct'], ['sd', 'i', 'sl', 'i', 'ke', 's'],
                            ['o', 'ra', 'v', 'oi', 'd', 'sp'], ['le', 'a', 'su', 'r', 'ei', 't'],
                            ['s', 'el', 'f', 'be', 'c', 'au'], ['se', 'i', 'ti', 's', 'pl', 'e'],
                            ['a', 'su', 'r', 'eb', 'u', 'tb'], ['ec', 'a', 'us', 'e', 'th', 'o'],
                            ['s', 'ew', 'h', 'od', 'o', 'no'], ['tk', 'n', 'ow', 'h', 'ow', 't'],
                            ['o', 'pu', 'r', 'su', 'e', 'pl'], ['ea', 's', 'ur', 'e', 'ra', 't'],
                            ['i', 'on', 'a', 'll', 'y', 'en'], ['co', 'u', 'nt', 'e', 'rc', 'o'],
                            ['n', 'se', 'q', 'ue', 'n', 'ce'], ['st', 'h', 'at', 'a', 're', 'e'],
                            ['x', 'tr', 'e', 'me', 'l', 'yp'], ['ai', 'n', 'fu', 'l', 'no', 'r'],
                            ['a', 'ga', 'i', 'ni', 's', 'th'], ['er', 'e', 'an', 'y', 'on', 'e'],
                            ['w', 'ho', 'l', 'ov', 'e', 'so'], ['rp', 'u', 'rs', 'u', 'es', 'o'],
                            ['r', 'de', 's', 'ir', 'e', 'st'], ['oo', 'b', 'ta', 'i', 'np', 'a'],
                            ['i', 'no', 'f', 'it', 's', 'el'], ['fb', 'e', 'ca', 'u', 'se', 'i'],
                            ['t', 'is', 'p', 'ai', 'n', 'bu'], ['tb', 'e', 'ca', 'u', 'se', 'o'],
                            ['c', 'ca', 's', 'io', 'n', 'al'], ['ly', 'c', 'ir', 'c', 'um', 's'],
                            ['t', 'an', 'c', 'es', 'o', 'cc'], ['ur', 'i', 'nw', 'h', 'ic', 'h'],
                            ['t', 'oi', 'l', 'an', 'd', 'pa'], ['in', 'c', 'an', 'p', 'ro', 'c'],
                            ['u', 're', 'h', 'im', 's', 'om'], ['eg', 'r', 'ea', 't', 'pl', 'e'], ['a', 'su', 'r', 'e']]
        },
        {
            "input": [
                'nsehnpienuhetgsnietleaanhofnisirersssneaeadrbeitoraxetgtaseilwigkeromyltvgrrannheveevronrinstreopblgreutrminnctrentssoiriesrfshjoyealfehxiipowteefskamyfradiqseequtatcenucafgasttentiatwatsowiovlswondhiareurthefofsafygtotrarafuiakefmekewnipicywhronearsnttasdbloemsmyibsnuinreienitmtldpdrstrhntafeiasettwleeeyiurmemnikpfaetrlmynewleahsayderasoontllsmoogwnhmhmadececeschatholiipprsoeexefmnishlelhoneonleaeseetheretinwhlalmapudtdsthsufeneeoetaasstneuwoltyessysoteenrihwiotieltmtehwhcfoiuliohdenothssetlecneysibabainoepmndenearahhetlytthaeaesuepecimaiatdbsealein',
                35142],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n', 'de', 'r'], ['fu', 'l', 'se', 'r', 'en'], ['i', 'ty', 'h', 'as', 't'],
                            ['ak', 'e', 'np', 'o', 'ss'], ['e', 'ss', 'i', 'on', 'o'], ['fm', 'y', 'en', 't', 'ir'],
                            ['e', 'so', 'u', 'll', 'i'], ['ke', 't', 'he', 's', 'es'], ['w', 'ee', 't', 'mo', 'r'],
                            ['ni', 'n', 'gs', 'o', 'fs'], ['p', 'ri', 'n', 'gw', 'h'], ['ic', 'h', 'ie', 'n', 'jo'],
                            ['y', 'wi', 't', 'hm', 'y'], ['wh', 'o', 'le', 'h', 'ea'], ['r', 'ti', 'a', 'ma', 'l'],
                            ['on', 'e', 'an', 'd', 'fe'], ['e', 'lt', 'h', 'ec', 'h'], ['ar', 'm', 'of', 'e', 'xi'],
                            ['s', 'te', 'n', 'ce', 'i'], ['nt', 'h', 'is', 's', 'po'], ['t', 'wh', 'i', 'ch', 'w'],
                            ['as', 'c', 're', 'a', 'te'], ['d', 'fo', 'r', 'th', 'e'], ['bl', 'i', 'ss', 'o', 'fs'],
                            ['o', 'ul', 's', 'li', 'k'], ['em', 'i', 'ne', 'i', 'am'], ['s', 'oh', 'a', 'pp', 'y'],
                            ['my', 'd', 'ea', 'r', 'fr'], ['i', 'en', 'd', 'so', 'a'], ['bs', 'o', 'rb', 'e', 'di'],
                            ['n', 'th', 'e', 'ex', 'q'], ['ui', 's', 'it', 'e', 'se'], ['n', 'se', 'o', 'fm', 'e'],
                            ['re', 't', 'ra', 'n', 'qu'], ['i', 'le', 'x', 'is', 't'], ['en', 'c', 'et', 'h', 'at'],
                            ['i', 'ne', 'g', 'le', 'c'], ['tm', 'y', 'ta', 'l', 'en'], ['t', 'si', 's', 'ho', 'u'],
                            ['ld', 'b', 'ei', 'n', 'ca'], ['p', 'ab', 'l', 'eo', 'f'], ['dr', 'a', 'wi', 'n', 'ga'],
                            ['s', 'in', 'g', 'le', 's'], ['tr', 'o', 'ke', 'a', 'tt'], ['h', 'ep', 'r', 'es', 'e'],
                            ['nt', 'm', 'om', 'e', 'nt'], ['a', 'nd', 'y', 'et', 'i'], ['fe', 'e', 'lt', 'h', 'at'],
                            ['i', 'ne', 'v', 'er', 'w'], ['as', 'a', 'gr', 'e', 'at'], ['e', 'ra', 'r', 'ti', 's'],
                            ['tt', 'h', 'an', 'n', 'ow'], ['w', 'he', 'n', 'wh', 'i'], ['le', 't', 'he', 'l', 'ov'],
                            ['e', 'ly', 'v', 'al', 'l'], ['ey', 't', 'ee', 'm', 'sw'], ['i', 'th', 'v', 'ap', 'o'],
                            ['ur', 'a', 'ro', 'u', 'nd'], ['m', 'ea', 'n', 'dt', 'h'], ['em', 'e', 'ri', 'd', 'ia'],
                            ['n', 'su', 'n', 'st', 'r'], ['ik', 'e', 'st', 'h', 'eu'], ['p', 'pe', 'r', 'su', 'r'],
                            ['fa', 'c', 'eo', 'f', 'th'], ['e', 'im', 'p', 'en', 'e'], ['tr', 'a', 'bl', 'e', 'fo'],
                            ['l', 'ia', 'g', 'eo', 'f'], ['my', 't', 're', 'e', 'sa'], ['n', 'db', 'u', 'ta', 'f'],
                            ['ew', 's', 'tr', 'a', 'yg'], ['l', 'ea', 'm', 'ss', 't'], ['ea', 'l', 'in', 't', 'ot'],
                            ['h', 'ei', 'n', 'ne', 'r'], ['sa', 'n', 'ct', 'u', 'ar'], ['y']]
        },
        {
            "input": [
                'futonueepjohanmntwthsohidieractmueogepaateanteyodtnpeefoetrlsawoissthenicymahtetteonedbsqfmxnetcankemfewtinlyinddstctrftameiyaenoentnihhmaltspoassimyaexoleiennwiontierrheeswuriefaeeoueaharrnpykergwttiexisreiemysoeseiatleiatreetvrawovmroeikrengdblotuntyeirsgshwhlecnwhdfsieaouieisgsipgaaomeasswhvthmiaheoamyfssndehsseesoieoonhceifooamrrbsretlesabstteltattialveaneufbltewtnerasisowfsnleearichrulsfreittencholinhnthgrhlelapnsuptheresearlakolltriyeadofhaseliaennsenetyldflerndiatnheturhstrimlsaainnseefmimonwirfeeiscblkppdthnquhtabdrsesyneeowleeaemrsupianygtct',
                325671894],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n', 'de', 'r', 'fu', 'l', 'se', 'r'],
                            ['en', 'i', 'ty', 'h', 'as', 't', 'ak', 'e', 'np'],
                            ['o', 'ss', 'e', 'ss', 'i', 'on', 'o', 'fm', 'y'],
                            ['en', 't', 'ir', 'e', 'so', 'u', 'll', 'i', 'ke'],
                            ['t', 'he', 's', 'es', 'w', 'ee', 't', 'mo', 'r'],
                            ['ni', 'n', 'gs', 'o', 'fs', 'p', 'ri', 'n', 'gw'],
                            ['h', 'ic', 'h', 'ie', 'n', 'jo', 'y', 'wi', 't'],
                            ['hm', 'y', 'wh', 'o', 'le', 'h', 'ea', 'r', 'ti'],
                            ['a', 'ma', 'l', 'on', 'e', 'an', 'd', 'fe', 'e'],
                            ['lt', 'h', 'ec', 'h', 'ar', 'm', 'of', 'e', 'xi'],
                            ['s', 'te', 'n', 'ce', 'i', 'nt', 'h', 'is', 's'],
                            ['po', 't', 'wh', 'i', 'ch', 'w', 'as', 'c', 're'],
                            ['a', 'te', 'd', 'fo', 'r', 'th', 'e', 'bl', 'i'],
                            ['ss', 'o', 'fs', 'o', 'ul', 's', 'li', 'k', 'em'],
                            ['i', 'ne', 'i', 'am', 's', 'oh', 'a', 'pp', 'y'],
                            ['my', 'd', 'ea', 'r', 'fr', 'i', 'en', 'd', 'so'],
                            ['a', 'bs', 'o', 'rb', 'e', 'di', 'n', 'th', 'e'],
                            ['ex', 'q', 'ui', 's', 'it', 'e', 'se', 'n', 'se'],
                            ['o', 'fm', 'e', 're', 't', 'ra', 'n', 'qu', 'i'],
                            ['le', 'x', 'is', 't', 'en', 'c', 'et', 'h', 'at'],
                            ['i', 'ne', 'g', 'le', 'c', 'tm', 'y', 'ta', 'l'],
                            ['en', 't', 'si', 's', 'ho', 'u', 'ld', 'b', 'ei'],
                            ['n', 'ca', 'p', 'ab', 'l', 'eo', 'f', 'dr', 'a'],
                            ['wi', 'n', 'ga', 's', 'in', 'g', 'le', 's', 'tr'],
                            ['o', 'ke', 'a', 'tt', 'h', 'ep', 'r', 'es', 'e'],
                            ['nt', 'm', 'om', 'e', 'nt', 'a', 'nd', 'y', 'et'],
                            ['i', 'fe', 'e', 'lt', 'h', 'at', 'i', 'ne', 'v'],
                            ['er', 'w', 'as', 'a', 'gr', 'e', 'at', 'e', 'ra'],
                            ['r', 'ti', 's', 'tt', 'h', 'an', 'n', 'ow', 'w'],
                            ['he', 'n', 'wh', 'i', 'le', 't', 'he', 'l', 'ov'],
                            ['e', 'ly', 'v', 'al', 'l', 'ey', 't', 'ee', 'm'],
                            ['sw', 'i', 'th', 'v', 'ap', 'o', 'ur', 'a', 'ro'],
                            ['u', 'nd', 'm', 'ea', 'n', 'dt', 'h', 'em', 'e'],
                            ['ri', 'd', 'ia', 'n', 'su', 'n', 'st', 'r', 'ik'],
                            ['e', 'st', 'h', 'eu', 'p', 'pe', 'r', 'su', 'r'],
                            ['fa', 'c', 'eo', 'f', 'th', 'e', 'im', 'p', 'en'],
                            ['e', 'tr', 'a', 'bl', 'e', 'fo', 'l', 'ia', 'g'],
                            ['eo', 'f', 'my', 't', 're', 'e', 'sa', 'n', 'db'],
                            ['u', 'ta', 'f', 'ew', 's', 'tr', 'a', 'yg', 'l'],
                            ['ea', 'm', 'ss', 't', 'ea', 'l', 'in', 't', 'ot'],
                            ['h', 'ei', 'n', 'ne', 'r', 'sa', 'n', 'ct', 'u'], ['ar', 'y']]
        },
        {
            "input": [
                'iploltteauleninandicoaoftxpetesreohehrbohasejsralitcisrcasnoosuuonccontaeinathoovrdeopasaupbecaluesnoiiocsatrbtetwamniengraiirnloueunsndduaihexoftstdmannesesdurfeiatbtodopueatyteqthxypnniahorsoeaifbetbusioianuchdnphgramuauhhakoncadpgsbivemcctemoacaofaretemufhpnoeliveasaupebuewtwtereaouncermefgaeneesusobielsaiccalmsowhlncuompesinoisefdisurpaowiyploheauntchtterruailupioctkoiselsleusehknoplrllnseseelulirewsoeirtnofeinausyctccianareeleutxoylisdnopeasnwalgatetysethlnggplthteernesrdiospebetsuehoowhrasienrueatraorsnylpurstnitcisteonrccritparimesu',
                25134],
            "answer": "butimustexplaintoyouhowallthismistakenideaofdenouncingpleasureandpraisingpainwasbornandiwillgiveyouacompleteaccountofthesystemandexpoundtheactualteachingsofthegreatexplorerofthetruththemasterbuilderofhumanhappinessnoonerejectsdislikesoravoidspleasureitselfbecauseitispleasurebutbecausethosewhodonotknowhowtopursuepleasurerationallyencounterconsequencesthatareextremelypainfulnoragainisthereanyonewholovesorpursuesordesirestoobtainpainofitselfbecauseitispainbutbecauseoccasionallycircumstancesoccurinwhichtoilandpaincanprocurehimsomegreatpleasure",
            "explanation": [['b', 'ut', 'i', 'mu', 's'], ['te', 'x', 'pl', 'a', 'in'], ['t', 'oy', 'o', 'uh', 'o'],
                            ['wa', 'l', 'lt', 'h', 'is'], ['m', 'is', 't', 'ak', 'e'], ['ni', 'd', 'ea', 'o', 'fd'],
                            ['e', 'no', 'u', 'nc', 'i'], ['ng', 'p', 'le', 'a', 'su'], ['r', 'ea', 'n', 'dp', 'r'],
                            ['ai', 's', 'in', 'g', 'pa'], ['i', 'nw', 'a', 'sb', 'o'], ['rn', 'a', 'nd', 'i', 'wi'],
                            ['l', 'lg', 'i', 've', 'y'], ['ou', 'a', 'co', 'm', 'pl'], ['e', 'te', 'a', 'cc', 'o'],
                            ['un', 't', 'of', 't', 'he'], ['s', 'ys', 't', 'em', 'a'], ['nd', 'e', 'xp', 'o', 'un'],
                            ['d', 'th', 'e', 'ac', 't'], ['ua', 'l', 'te', 'a', 'ch'], ['i', 'ng', 's', 'of', 't'],
                            ['he', 'g', 're', 'a', 'te'], ['x', 'pl', 'o', 're', 'r'], ['of', 't', 'he', 't', 'ru'],
                            ['t', 'ht', 'h', 'em', 'a'], ['st', 'e', 'rb', 'u', 'il'], ['d', 'er', 'o', 'fh', 'u'],
                            ['ma', 'n', 'ha', 'p', 'pi'], ['n', 'es', 's', 'no', 'o'], ['ne', 'r', 'ej', 'e', 'ct'],
                            ['s', 'di', 's', 'li', 'k'], ['es', 'o', 'ra', 'v', 'oi'], ['d', 'sp', 'l', 'ea', 's'],
                            ['ur', 'e', 'it', 's', 'el'], ['f', 'be', 'c', 'au', 's'], ['ei', 't', 'is', 'p', 'le'],
                            ['a', 'su', 'r', 'eb', 'u'], ['tb', 'e', 'ca', 'u', 'se'], ['t', 'ho', 's', 'ew', 'h'],
                            ['od', 'o', 'no', 't', 'kn'], ['o', 'wh', 'o', 'wt', 'o'], ['pu', 'r', 'su', 'e', 'pl'],
                            ['e', 'as', 'u', 're', 'r'], ['at', 'i', 'on', 'a', 'll'], ['y', 'en', 'c', 'ou', 'n'],
                            ['te', 'r', 'co', 'n', 'se'], ['q', 'ue', 'n', 'ce', 's'], ['th', 'a', 'ta', 'r', 'ee'],
                            ['x', 'tr', 'e', 'me', 'l'], ['yp', 'a', 'in', 'f', 'ul'], ['n', 'or', 'a', 'ga', 'i'],
                            ['ni', 's', 'th', 'e', 're'], ['a', 'ny', 'o', 'ne', 'w'], ['ho', 'l', 'ov', 'e', 'so'],
                            ['r', 'pu', 'r', 'su', 'e'], ['so', 'r', 'de', 's', 'ir'], ['e', 'st', 'o', 'ob', 't'],
                            ['ai', 'n', 'pa', 'i', 'no'], ['f', 'it', 's', 'el', 'f'], ['be', 'c', 'au', 's', 'ei'],
                            ['t', 'is', 'p', 'ai', 'n'], ['bu', 't', 'be', 'c', 'au'], ['s', 'eo', 'c', 'ca', 's'],
                            ['io', 'n', 'al', 'l', 'yc'], ['i', 'rc', 'u', 'ms', 't'], ['an', 'c', 'es', 'o', 'cc'],
                            ['u', 'ri', 'n', 'wh', 'i'], ['ch', 't', 'oi', 'l', 'an'], ['d', 'pa', 'i', 'nc', 'a'],
                            ['np', 'r', 'oc', 'u', 're'], ['h', 'im', 's', 'om', 'e'], ['gr', 'e', 'at', 'p', 'le'],
                            ['a', 'su', 'r', 'e']]
        },
        {
            "input": [
                'arhwotrfcesasotvensedvemovaasscsleomeruwsrndehtsgeirattrainrairouvannhetdtpthiaretttemaancalndebplssihsaltidicyfwaddmnomnokdanrheearenbkrihofalagealamnytauptenriasiscarythosfttracotelbxtaylosggectntruanrieflhcepwieyrlapeoufbeeunaheiliniailisteiokrhtoheigegasvddoeialitceeiaaman',
                34512],
            "answer": "farfarawaybehindthewordmountainsfarfromthecountriesvokaliaandconsonantiatherelivetheblindtextsseparatedtheyliveinbookmarksgroverightatthecoastofthesemanticsalargelanguageoceanasmallrivernameddudenflowsbytheirplaceandsuppliesitwiththenecessaryregelialiaitisaparadisematiccountry",
            "explanation": [['f', 'ar', 'f', 'ar', 'a'], ['wa', 'y', 'be', 'h', 'in'], ['d', 'th', 'e', 'wo', 'r'],
                            ['dm', 'o', 'un', 't', 'ai'], ['n', 'sf', 'a', 'rf', 'r'], ['om', 't', 'he', 'c', 'ou'],
                            ['n', 'tr', 'i', 'es', 'v'], ['ok', 'a', 'li', 'a', 'an'], ['d', 'co', 'n', 'so', 'n'],
                            ['an', 't', 'ia', 't', 'he'], ['r', 'el', 'i', 've', 't'], ['he', 'b', 'li', 'n', 'dt'],
                            ['e', 'xt', 's', 'se', 'p'], ['ar', 'a', 'te', 'd', 'th'], ['e', 'yl', 'i', 've', 'i'],
                            ['nb', 'o', 'ok', 'm', 'ar'], ['k', 'sg', 'r', 'ov', 'e'], ['ri', 'g', 'ht', 'a', 'tt'],
                            ['h', 'ec', 'o', 'as', 't'], ['of', 't', 'he', 's', 'em'], ['a', 'nt', 'i', 'cs', 'a'],
                            ['la', 'r', 'ge', 'l', 'an'], ['g', 'ua', 'g', 'eo', 'c'], ['ea', 'n', 'as', 'm', 'al'],
                            ['l', 'ri', 'v', 'er', 'n'], ['am', 'e', 'dd', 'u', 'de'], ['n', 'fl', 'o', 'ws', 'b'],
                            ['yt', 'h', 'ei', 'r', 'pl'], ['a', 'ce', 'a', 'nd', 's'], ['up', 'p', 'li', 'e', 'si'],
                            ['t', 'wi', 't', 'ht', 'h'], ['en', 'e', 'ce', 's', 'sa'], ['r', 'yr', 'e', 'ge', 'l'],
                            ['ia', 'l', 'ia', 'i', 'ti'], ['s', 'ap', 'a', 'ra', 'd'], ['is', 'e', 'ma', 't', 'ic'],
                            ['c', 'ou', 'n', 'tr', 'y']]
        },
        {
            "input": ['cfoozyqowmaltkbxveduinpsaherjurog', 35241],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui', 'c'], ['kb', 'r', 'ow', 'n', 'fo'], ['x', 'ju', 'm', 'ps', 'o'],
                            ['ve', 'r', 'al', 'a', 'zy'], ['d', 'og']]
        },
        {
            "input": ['heoaluiuzyqxjarovtnfrowekbsogcmpd', 51328746],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui', 'c', 'kb', 'r', 'ow'], ['nf', 'o', 'xj', 'u', 'mp', 's', 'ov', 'e'],
                            ['r', 'al', 'a', 'zy', 'd', 'og']]
        },
        {
            "input": ['herjurogcfoozyuinpsatkbxvedqowmal', 41532],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui', 'c'], ['kb', 'r', 'ow', 'n', 'fo'], ['x', 'ju', 'm', 'ps', 'o'],
                            ['ve', 'r', 'al', 'a', 'zy'], ['d', 'og']]
        },
        {
            "input": ['tcknmprdouiwjuezyhebfosalgqroxova', 1342],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui'], ['ck', 'b', 'ro', 'w'], ['n', 'fo', 'x', 'ju'],
                            ['mp', 's', 'ov', 'e'], ['r', 'al', 'a', 'zy'], ['do', 'g']]
        },
    ]
}
