"""
TESTS is a dict with all you tests.
Keys for this will be categories' names.
Each test is dict with
    "input" -- input data for user function
    "answer" -- your right answer
    "explanation" -- not necessary key, it's using for additional info in animation.
"""

TESTS = {
    "Basics": [
        {
            "input": ['oruoreemdstmioitlpslam', 4123],
            "answer": "loremipsumdolorsitamet",
            "explanation": [['l', 'or', 'e', 'mi'], ['ps', 'u', 'md', 'o'], ['l', 'or', 's', 'it'], ['am', 'e', 't']]
        },
        {
            "input": ['kicheco', 23415],
            "answer": "checkio",
            "explanation": [['c', 'he', 'c', 'ki', 'o']]
        },
        {
            "input": ['hreulhemooowywiotorwaolmmr', 123],
            "answer": "howareyouwillhometommorrow",
            "explanation": [['h', 'ow', 'a'], ['re', 'y', 'o'], ['u', 'wi', 'l'], ['lh', 'o', 'm'], ['e', 'to', 'm'],
                            ['mo', 'r', 'r'], ['o', 'w']]
        },
    ],
    "Extra": [
        {
            "input": ['tuibnfjsorzyghecrooumvaldqkwxpeao', 123],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q'], ['ui', 'c', 'k'], ['b', 'ro', 'w'], ['nf', 'o', 'x'], ['j', 'um', 'p'],
                            ['so', 'v', 'e'], ['r', 'al', 'a'], ['zy', 'd', 'o'], ['g']]
        },
        {
            "input": [
                'nreatrrunfmeerrmnhranfadhehbhtadbisehwaaeretoftorgmsmddoelrsboeroouklieleewngedeesfstglyvseyofningwooeadtrddiiinilidteaeciellndyntcebsblimesanogwokeumshanintbheskeidhlouslyydiaostedhettdrlymmenaroeefsfoiahvaymaceshtdsolimidhifnindcodademenehrsfblhimsnholelarbfhiitlbrsdovrctiodaroaneido',
                465213],
            "answer": "onemorningwhengregorsamsawokefromtroubleddreamshefoundhimselftransformedinhisbedintoahorribleverminhelayonhisarmourlikebackandifheliftedhisheadalittlehecouldseehisbrownbellyslightlydomedanddividedbyarchesintostiffsectionsthebeddingwashardlyabletocoveritandseemedreadytoslideoffanymoment",
            "explanation": [['o', 'ne', 'm', 'or', 'n', 'in'], ['gw', 'h', 'en', 'g', 're', 'g'],
                            ['o', 'rs', 'a', 'ms', 'a', 'wo'], ['ke', 'f', 'ro', 'm', 'tr', 'o'],
                            ['u', 'bl', 'e', 'dd', 'r', 'ea'], ['ms', 'h', 'ef', 'o', 'un', 'd'],
                            ['h', 'im', 's', 'el', 'f', 'tr'], ['an', 's', 'fo', 'r', 'me', 'd'],
                            ['i', 'nh', 'i', 'sb', 'e', 'di'], ['nt', 'o', 'ah', 'o', 'rr', 'i'],
                            ['b', 'le', 'v', 'er', 'm', 'in'], ['he', 'l', 'ay', 'o', 'nh', 'i'],
                            ['s', 'ar', 'm', 'ou', 'r', 'li'], ['ke', 'b', 'ac', 'k', 'an', 'd'],
                            ['i', 'fh', 'e', 'li', 'f', 'te'], ['dh', 'i', 'sh', 'e', 'ad', 'a'],
                            ['l', 'it', 't', 'le', 'h', 'ec'], ['ou', 'l', 'ds', 'e', 'eh', 'i'],
                            ['s', 'br', 'o', 'wn', 'b', 'el'], ['ly', 's', 'li', 'g', 'ht', 'l'],
                            ['y', 'do', 'm', 'ed', 'a', 'nd'], ['di', 'v', 'id', 'e', 'db', 'y'],
                            ['a', 'rc', 'h', 'es', 'i', 'nt'], ['os', 't', 'if', 'f', 'se', 'c'],
                            ['t', 'io', 'n', 'st', 'h', 'eb'], ['ed', 'd', 'in', 'g', 'wa', 's'],
                            ['h', 'ar', 'd', 'ly', 'a', 'bl'], ['et', 'o', 'co', 'v', 'er', 'i'],
                            ['t', 'an', 'd', 'se', 'e', 'me'], ['dr', 'e', 'ad', 'y', 'to', 's'],
                            ['l', 'id', 'e', 'of', 'f', 'an'], ['ym', 'o', 'me', 'n', 't']]
        },
        {
            "input": [
                'adeuretstesssofereukeeweminoriwhijityleaamondeecrexteihpohwaredrblsoulmiiohpdefndarbieeutenfmenqlstcatecttntsldipaeranineoktpreomtyefthiersearishoweilhveveyeitaraueateriunrstursfofeenrefioftsabfetglmeanhenanuworlsnyhanpeiomntslltseeorgfsnhieoyhwhhrtaneflthmoiennisticseafthiofliknamaymarisbsentxissseetruexeetiglmalshobncbofwgagstethenteanteeanewagtartanwnweellaltmshporndnheiansikhppuactimeaboagmrenutwraessltoiercarnfeiakosnyioihstnspgcnwmoeilaehafsctswhctoessseespyreoodhqieoraiinhneyeiuealdislraesmndiltvarettnhhtoylewvuomdmdsteeerehptlleyedasyatitnsty',
                123],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n'], ['de', 'r', 'f'], ['u', 'ls', 'e'], ['re', 'n', 'i'], ['t', 'yh', 'a'],
                            ['st', 'a', 'k'], ['e', 'np', 'o'], ['ss', 'e', 's'], ['s', 'io', 'n'], ['of', 'm', 'y'],
                            ['e', 'nt', 'i'], ['re', 's', 'o'], ['u', 'll', 'i'], ['ke', 't', 'h'], ['e', 'se', 's'],
                            ['we', 'e', 't'], ['m', 'or', 'n'], ['in', 'g', 's'], ['o', 'fs', 'p'], ['ri', 'n', 'g'],
                            ['w', 'hi', 'c'], ['hi', 'e', 'n'], ['j', 'oy', 'w'], ['it', 'h', 'm'], ['y', 'wh', 'o'],
                            ['le', 'h', 'e'], ['a', 'rt', 'i'], ['am', 'a', 'l'], ['o', 'ne', 'a'], ['nd', 'f', 'e'],
                            ['e', 'lt', 'h'], ['ec', 'h', 'a'], ['r', 'mo', 'f'], ['ex', 'i', 's'], ['t', 'en', 'c'],
                            ['ei', 'n', 't'], ['h', 'is', 's'], ['po', 't', 'w'], ['h', 'ic', 'h'], ['wa', 's', 'c'],
                            ['r', 'ea', 't'], ['ed', 'f', 'o'], ['r', 'th', 'e'], ['bl', 'i', 's'], ['s', 'of', 's'],
                            ['ou', 'l', 's'], ['l', 'ik', 'e'], ['mi', 'n', 'e'], ['i', 'am', 's'], ['oh', 'a', 'p'],
                            ['p', 'ym', 'y'], ['de', 'a', 'r'], ['f', 'ri', 'e'], ['nd', 's', 'o'], ['a', 'bs', 'o'],
                            ['rb', 'e', 'd'], ['i', 'nt', 'h'], ['ee', 'x', 'q'], ['u', 'is', 'i'], ['te', 's', 'e'],
                            ['n', 'se', 'o'], ['fm', 'e', 'r'], ['e', 'tr', 'a'], ['nq', 'u', 'i'], ['l', 'ex', 'i'],
                            ['st', 'e', 'n'], ['c', 'et', 'h'], ['at', 'i', 'n'], ['e', 'gl', 'e'], ['ct', 'm', 'y'],
                            ['t', 'al', 'e'], ['nt', 's', 'i'], ['s', 'ho', 'u'], ['ld', 'b', 'e'], ['i', 'nc', 'a'],
                            ['pa', 'b', 'l'], ['e', 'of', 'd'], ['ra', 'w', 'i'], ['n', 'ga', 's'], ['in', 'g', 'l'],
                            ['e', 'st', 'r'], ['ok', 'e', 'a'], ['t', 'th', 'e'], ['pr', 'e', 's'], ['e', 'nt', 'm'],
                            ['om', 'e', 'n'], ['t', 'an', 'd'], ['ye', 't', 'i'], ['f', 'ee', 'l'], ['th', 'a', 't'],
                            ['i', 'ne', 'v'], ['er', 'w', 'a'], ['s', 'ag', 'r'], ['ea', 't', 'e'], ['r', 'ar', 't'],
                            ['is', 't', 't'], ['h', 'an', 'n'], ['ow', 'w', 'h'], ['e', 'nw', 'h'], ['il', 'e', 't'],
                            ['h', 'el', 'o'], ['ve', 'l', 'y'], ['v', 'al', 'l'], ['ey', 't', 'e'], ['e', 'ms', 'w'],
                            ['it', 'h', 'v'], ['a', 'po', 'u'], ['ra', 'r', 'o'], ['u', 'nd', 'm'], ['ea', 'n', 'd'],
                            ['t', 'he', 'm'], ['er', 'i', 'd'], ['i', 'an', 's'], ['un', 's', 't'], ['r', 'ik', 'e'],
                            ['st', 'h', 'e'], ['u', 'pp', 'e'], ['rs', 'u', 'r'], ['f', 'ac', 'e'], ['of', 't', 'h'],
                            ['e', 'im', 'p'], ['en', 'e', 't'], ['r', 'ab', 'l'], ['ef', 'o', 'l'], ['i', 'ag', 'e'],
                            ['of', 'm', 'y'], ['t', 're', 'e'], ['sa', 'n', 'd'], ['b', 'ut', 'a'], ['fe', 'w', 's'],
                            ['t', 'ra', 'y'], ['gl', 'e', 'a'], ['m', 'ss', 't'], ['ea', 'l', 'i'], ['n', 'to', 't'],
                            ['he', 'i', 'n'], ['n', 'er', 's'], ['an', 'c', 't'], ['u', 'ar', 'y']]
        },
        {
            "input": [
                'afuntasnotlletmginhwihrtoeehxiespcearsslinoydibsiqusmenistgltisbabrsitthentthaereranethlytiurdheitrhsuopebagtdbwleethrarresoonuhenrcywalfcecsiroiumsmradxefaxeeysdpdastseetvgahheeewontdstremaiynegtoeuwolitksefiriseosogietolinelarsinohwtthoslehaeenontienrquthaealheilawnroentaiftrwatinnweyvethamemanieurftnleereustaalesayderhapsiesotweispijoyheandeofnhihscfblokempyfsoeeeteorlecinmntlcafngeeaeomyelesarttwilvllsapundiunspeceirolmsafaysntnctnseyensmyekesrnfwhnhmeamathmtettwaedefsiiapardrbhsisetientcteouneoiglkprmndeinatesowhloaemvroaerskepfahetfofetarmsiinn',
                13542],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n', 'de', 'r'], ['fu', 'l', 'se', 'r', 'e'], ['n', 'it', 'y', 'ha', 's'],
                            ['ta', 'k', 'en', 'p', 'o'], ['s', 'se', 's', 'si', 'o'], ['no', 'f', 'my', 'e', 'n'],
                            ['t', 'ir', 'e', 'so', 'u'], ['ll', 'i', 'ke', 't', 'h'], ['e', 'se', 's', 'we', 'e'],
                            ['tm', 'o', 'rn', 'i', 'n'], ['g', 'so', 'f', 'sp', 'r'], ['in', 'g', 'wh', 'i', 'c'],
                            ['h', 'ie', 'n', 'jo', 'y'], ['wi', 't', 'hm', 'y', 'w'], ['h', 'ol', 'e', 'he', 'a'],
                            ['rt', 'i', 'am', 'a', 'l'], ['o', 'ne', 'a', 'nd', 'f'], ['ee', 'l', 'th', 'e', 'c'],
                            ['h', 'ar', 'm', 'of', 'e'], ['xi', 's', 'te', 'n', 'c'], ['e', 'in', 't', 'hi', 's'],
                            ['sp', 'o', 'tw', 'h', 'i'], ['c', 'hw', 'a', 'sc', 'r'], ['ea', 't', 'ed', 'f', 'o'],
                            ['r', 'th', 'e', 'bl', 'i'], ['ss', 'o', 'fs', 'o', 'u'], ['l', 'sl', 'i', 'ke', 'm'],
                            ['in', 'e', 'ia', 'm', 's'], ['o', 'ha', 'p', 'py', 'm'], ['yd', 'e', 'ar', 'f', 'r'],
                            ['i', 'en', 'd', 'so', 'a'], ['bs', 'o', 'rb', 'e', 'd'], ['i', 'nt', 'h', 'ee', 'x'],
                            ['qu', 'i', 'si', 't', 'e'], ['s', 'en', 's', 'eo', 'f'], ['me', 'r', 'et', 'r', 'a'],
                            ['n', 'qu', 'i', 'le', 'x'], ['is', 't', 'en', 'c', 'e'], ['t', 'ha', 't', 'in', 'e'],
                            ['gl', 'e', 'ct', 'm', 'y'], ['t', 'al', 'e', 'nt', 's'], ['is', 'h', 'ou', 'l', 'd'],
                            ['b', 'ei', 'n', 'ca', 'p'], ['ab', 'l', 'eo', 'f', 'd'], ['r', 'aw', 'i', 'ng', 'a'],
                            ['si', 'n', 'gl', 'e', 's'], ['t', 'ro', 'k', 'ea', 't'], ['th', 'e', 'pr', 'e', 's'],
                            ['e', 'nt', 'm', 'om', 'e'], ['nt', 'a', 'nd', 'y', 'e'], ['t', 'if', 'e', 'el', 't'],
                            ['ha', 't', 'in', 'e', 'v'], ['e', 'rw', 'a', 'sa', 'g'], ['re', 'a', 'te', 'r', 'a'],
                            ['r', 'ti', 's', 'tt', 'h'], ['an', 'n', 'ow', 'w', 'h'], ['e', 'nw', 'h', 'il', 'e'],
                            ['th', 'e', 'lo', 'v', 'e'], ['l', 'yv', 'a', 'll', 'e'], ['yt', 'e', 'em', 's', 'w'],
                            ['i', 'th', 'v', 'ap', 'o'], ['ur', 'a', 'ro', 'u', 'n'], ['d', 'me', 'a', 'nd', 't'],
                            ['he', 'm', 'er', 'i', 'd'], ['i', 'an', 's', 'un', 's'], ['tr', 'i', 'ke', 's', 't'],
                            ['h', 'eu', 'p', 'pe', 'r'], ['su', 'r', 'fa', 'c', 'e'], ['o', 'ft', 'h', 'ei', 'm'],
                            ['pe', 'n', 'et', 'r', 'a'], ['b', 'le', 'f', 'ol', 'i'], ['ag', 'e', 'of', 'm', 'y'],
                            ['t', 're', 'e', 'sa', 'n'], ['db', 'u', 'ta', 'f', 'e'], ['w', 'st', 'r', 'ay', 'g'],
                            ['le', 'a', 'ms', 's', 't'], ['e', 'al', 'i', 'nt', 'o'], ['th', 'e', 'in', 'n', 'e'],
                            ['r', 'sa', 'n', 'ct', 'u'], ['ar', 'y']]
        },
        {
            "input": ['lempmdlsiatcncttraiscnliaeacmooguaetorannmsorisuoortmeoseeuedpiigetennomdlilegdloeeaasa', 12],
            "answer": "loremipsumdolorsitametconsectetueradipiscingelitaeneancommodoligulaegetdoloraeneanmassa",
            "explanation": [['l', 'or'], ['em', 'i'], ['p', 'su'], ['md', 'o'], ['l', 'or'], ['si', 't'], ['a', 'me'],
                            ['tc', 'o'], ['n', 'se'], ['ct', 'e'], ['t', 'ue'], ['ra', 'd'], ['i', 'pi'], ['sc', 'i'],
                            ['n', 'ge'], ['li', 't'], ['a', 'en'], ['ea', 'n'], ['c', 'om'], ['mo', 'd'], ['o', 'li'],
                            ['gu', 'l'], ['a', 'eg'], ['et', 'd'], ['o', 'lo'], ['ra', 'e'], ['n', 'ea'], ['nm', 'a'],
                            ['s', 'sa']]
        },
        {
            "input": [
                'fawhewonsrcoialdnativbexpdtiookeraoatanalagnalnauowhacsestecrliiarecoyarainounfomuesiconheelitarhveksgittshetlaneosrimdeseieupihteyratiamauarethmaifheroknsoaeledtetelnbrovtecfemsgeaealerdfltpldliienageaapsicrfybdrdtartntvaantirthnssaeyimarghhtosicrgucmavednbyranptwhsselisditnt',
                1243],
            "answer": "farfarawaybehindthewordmountainsfarfromthecountriesvokaliaandconsonantiatherelivetheblindtextsseparatedtheyliveinbookmarksgroverightatthecoastofthesemanticsalargelanguageoceanasmallrivernameddudenflowsbytheirplaceandsuppliesitwiththenecessaryregelialiaitisaparadisematiccountry",
            "explanation": [['f', 'ar', 'f', 'ar'], ['aw', 'a', 'yb', 'e'], ['h', 'in', 'd', 'th'],
                            ['ew', 'o', 'rd', 'm'], ['o', 'un', 't', 'ai'], ['ns', 'f', 'ar', 'f'],
                            ['r', 'om', 't', 'he'], ['co', 'u', 'nt', 'r'], ['i', 'es', 'v', 'ok'],
                            ['al', 'i', 'aa', 'n'], ['d', 'co', 'n', 'so'], ['na', 'n', 'ti', 'a'],
                            ['t', 'he', 'r', 'el'], ['iv', 'e', 'th', 'e'], ['b', 'li', 'n', 'dt'],
                            ['ex', 't', 'ss', 'e'], ['p', 'ar', 'a', 'te'], ['dt', 'h', 'ey', 'l'],
                            ['i', 've', 'i', 'nb'], ['oo', 'k', 'ma', 'r'], ['k', 'sg', 'r', 'ov'],
                            ['er', 'i', 'gh', 't'], ['a', 'tt', 'h', 'ec'], ['oa', 's', 'to', 'f'],
                            ['t', 'he', 's', 'em'], ['an', 't', 'ic', 's'], ['a', 'la', 'r', 'ge'],
                            ['la', 'n', 'gu', 'a'], ['g', 'eo', 'c', 'ea'], ['na', 's', 'ma', 'l'],
                            ['l', 'ri', 'v', 'er'], ['na', 'm', 'ed', 'd'], ['u', 'de', 'n', 'fl'],
                            ['ow', 's', 'by', 't'], ['h', 'ei', 'r', 'pl'], ['ac', 'e', 'an', 'd'],
                            ['s', 'up', 'p', 'li'], ['es', 'i', 'tw', 'i'], ['t', 'ht', 'h', 'en'],
                            ['ec', 'e', 'ss', 'a'], ['r', 'yr', 'e', 'ge'], ['li', 'a', 'li', 'a'],
                            ['i', 'ti', 's', 'ap'], ['ar', 'a', 'di', 's'], ['e', 'ma', 't', 'ic'],
                            ['co', 'u', 'nt', 'r'], ['y']]
        },
        {
            "input": [
                'oornenesaaefmubdamendmftnrmisbiahrevmelosaoikandhftheallecdshrobysgydeddibycinsfststbinardatovtasedaosdfamntmihrrskooeehuilaodidorlrhyimlbafidhatelebnlilmnvdrsofcnedwayeoidmetifyenengwggomwortrldrsfohsersfenhentoibeinanhrureckieleisdithoueiswellhtodaideahettieiohedgshlblcerneerdyleonom',
                132],
            "answer": "onemorningwhengregorsamsawokefromtroubleddreamshefoundhimselftransformedinhisbedintoahorribleverminhelayonhisarmourlikebackandifheliftedhisheadalittlehecouldseehisbrownbellyslightlydomedanddividedbyarchesintostiffsectionsthebeddingwashardlyabletocoveritandseemedreadytoslideoffanymoment",
            "explanation": [['o', 'ne', 'm'], ['or', 'n', 'i'], ['n', 'gw', 'h'], ['en', 'g', 'r'], ['e', 'go', 'r'],
                            ['sa', 'm', 's'], ['a', 'wo', 'k'], ['ef', 'r', 'o'], ['m', 'tr', 'o'], ['ub', 'l', 'e'],
                            ['d', 'dr', 'e'], ['am', 's', 'h'], ['e', 'fo', 'u'], ['nd', 'h', 'i'], ['m', 'se', 'l'],
                            ['ft', 'r', 'a'], ['n', 'sf', 'o'], ['rm', 'e', 'd'], ['i', 'nh', 'i'], ['sb', 'e', 'd'],
                            ['i', 'nt', 'o'], ['ah', 'o', 'r'], ['r', 'ib', 'l'], ['ev', 'e', 'r'], ['m', 'in', 'h'],
                            ['el', 'a', 'y'], ['o', 'nh', 'i'], ['sa', 'r', 'm'], ['o', 'ur', 'l'], ['ik', 'e', 'b'],
                            ['a', 'ck', 'a'], ['nd', 'i', 'f'], ['h', 'el', 'i'], ['ft', 'e', 'd'], ['h', 'is', 'h'],
                            ['ea', 'd', 'a'], ['l', 'it', 't'], ['le', 'h', 'e'], ['c', 'ou', 'l'], ['ds', 'e', 'e'],
                            ['h', 'is', 'b'], ['ro', 'w', 'n'], ['b', 'el', 'l'], ['ys', 'l', 'i'], ['g', 'ht', 'l'],
                            ['yd', 'o', 'm'], ['e', 'da', 'n'], ['dd', 'i', 'v'], ['i', 'de', 'd'], ['by', 'a', 'r'],
                            ['c', 'he', 's'], ['in', 't', 'o'], ['s', 'ti', 'f'], ['fs', 'e', 'c'], ['t', 'io', 'n'],
                            ['st', 'h', 'e'], ['b', 'ed', 'd'], ['in', 'g', 'w'], ['a', 'sh', 'a'], ['rd', 'l', 'y'],
                            ['a', 'bl', 'e'], ['to', 'c', 'o'], ['v', 'er', 'i'], ['ta', 'n', 'd'], ['s', 'ee', 'm'],
                            ['ed', 'r', 'e'], ['a', 'dy', 't'], ['os', 'l', 'i'], ['d', 'eo', 'f'], ['fa', 'n', 'y'],
                            ['m', 'om', 'e'], ['nt']]
        },
        {
            "input": [
                'omongwereoamakertruedrmseunhsefanfmeiisentarrbvemheanhsmorkeaanielfdhsadltlhoudehsowblylhtymeadiidbaheiosisetnshediwahdlaetcertdsedratoleofymmtnerinhnggrsswofomobldeahfodimltrsordnhbdiohoilerinlyoiarulibckdfhiteiheaiteeclseibrnelsigldodndvdeyrcsnttffciotebdngsarybloovianemeedysidfanoen',
                12],
            "answer": "onemorningwhengregorsamsawokefromtroubleddreamshefoundhimselftransformedinhisbedintoahorribleverminhelayonhisarmourlikebackandifheliftedhisheadalittlehecouldseehisbrownbellyslightlydomedanddividedbyarchesintostiffsectionsthebeddingwashardlyabletocoveritandseemedreadytoslideoffanymoment",
            "explanation": [['o', 'ne'], ['mo', 'r'], ['n', 'in'], ['gw', 'h'], ['e', 'ng'], ['re', 'g'], ['o', 'rs'],
                            ['am', 's'], ['a', 'wo'], ['ke', 'f'], ['r', 'om'], ['tr', 'o'], ['u', 'bl'], ['ed', 'd'],
                            ['r', 'ea'], ['ms', 'h'], ['e', 'fo'], ['un', 'd'], ['h', 'im'], ['se', 'l'], ['f', 'tr'],
                            ['an', 's'], ['f', 'or'], ['me', 'd'], ['i', 'nh'], ['is', 'b'], ['e', 'di'], ['nt', 'o'],
                            ['a', 'ho'], ['rr', 'i'], ['b', 'le'], ['ve', 'r'], ['m', 'in'], ['he', 'l'], ['a', 'yo'],
                            ['nh', 'i'], ['s', 'ar'], ['mo', 'u'], ['r', 'li'], ['ke', 'b'], ['a', 'ck'], ['an', 'd'],
                            ['i', 'fh'], ['el', 'i'], ['f', 'te'], ['dh', 'i'], ['s', 'he'], ['ad', 'a'], ['l', 'it'],
                            ['tl', 'e'], ['h', 'ec'], ['ou', 'l'], ['d', 'se'], ['eh', 'i'], ['s', 'br'], ['ow', 'n'],
                            ['b', 'el'], ['ly', 's'], ['l', 'ig'], ['ht', 'l'], ['y', 'do'], ['me', 'd'], ['a', 'nd'],
                            ['di', 'v'], ['i', 'de'], ['db', 'y'], ['a', 'rc'], ['he', 's'], ['i', 'nt'], ['os', 't'],
                            ['i', 'ff'], ['se', 'c'], ['t', 'io'], ['ns', 't'], ['h', 'eb'], ['ed', 'd'], ['i', 'ng'],
                            ['wa', 's'], ['h', 'ar'], ['dl', 'y'], ['a', 'bl'], ['et', 'o'], ['c', 'ov'], ['er', 'i'],
                            ['t', 'an'], ['ds', 'e'], ['e', 'me'], ['dr', 'e'], ['a', 'dy'], ['to', 's'], ['l', 'id'],
                            ['eo', 'f'], ['f', 'an'], ['ym', 'o'], ['m', 'en'], ['t']]
        },
        {
            "input": ['qowuraouinmplgherxjeydcfsatkboovz', 53124],
            "answer": "thequickbrownfoxjumpsoveralazydog",
            "explanation": [['t', 'he', 'q', 'ui', 'c'], ['kb', 'r', 'ow', 'n', 'f'], ['o', 'xj', 'u', 'mp', 's'],
                            ['ov', 'e', 'ra', 'l', 'a'], ['z', 'yd', 'o', 'g']]
        },
        {
            "input": [
                'fuynpnireeesgwowhiancxitwhethsemheaodiiseaisttmieiogarepmettasaanhovythodtaikeeonfoydbrsstsariteiotikwngnnjyrteheeintcrrofksoddsequntrxhactsblensthmoyhawerhnwlleiarndirppcpeefmnstmtorywoeassfmoheofscwiemaeareishtelulepprbshitmqunneahoadrnkesntenertiwleyeepndmsutsuhtrareaygaeitalshosoesttmohiyoladfhsthicaeboinarfantsofnteiytsncfsioreeifiagrnoieltvauhenesrftelitutatehncnretesyulsrnphithelelmncswadissiayieoeeeericegleupaaglaenaelveaswhtvamoumernhereiageefellinuadenaksenlesiriehmaontofeposfoslimmynrbxseeletlenldbwietttndtertttehelswreaistufamblosaweanner',
                435621],
            "answer": "awonderfulserenityhastakenpossessionofmyentiresoullikethesesweetmorningsofspringwhichienjoywithmywholeheartiamaloneandfeelthecharmofexistenceinthisspotwhichwascreatedfortheblissofsoulslikemineiamsohappymydearfriendsoabsorbedintheexquisitesenseofmeretranquilexistencethatineglectmytalentsishouldbeincapableofdrawingasinglestrokeatthepresentmomentandyetifeelthatineverwasagreaterartistthannowwhenwhilethelovelyvalleyteemswithvapouraroundmeandthemeridiansunstrikestheuppersurfaceoftheimpenetrablefoliageofmytreesandbutafewstraygleamsstealintotheinnersanctuary",
            "explanation": [['a', 'wo', 'n', 'de', 'r', 'fu'], ['ls', 'e', 're', 'n', 'it', 'y'],
                            ['h', 'as', 't', 'ak', 'e', 'np'], ['os', 's', 'es', 's', 'io', 'n'],
                            ['o', 'fm', 'y', 'en', 't', 'ir'], ['es', 'o', 'ul', 'l', 'ik', 'e'],
                            ['t', 'he', 's', 'es', 'w', 'ee'], ['tm', 'o', 'rn', 'i', 'ng', 's'],
                            ['o', 'fs', 'p', 'ri', 'n', 'gw'], ['hi', 'c', 'hi', 'e', 'nj', 'o'],
                            ['y', 'wi', 't', 'hm', 'y', 'wh'], ['ol', 'e', 'he', 'a', 'rt', 'i'],
                            ['a', 'ma', 'l', 'on', 'e', 'an'], ['df', 'e', 'el', 't', 'he', 'c'],
                            ['h', 'ar', 'm', 'of', 'e', 'xi'], ['st', 'e', 'nc', 'e', 'in', 't'],
                            ['h', 'is', 's', 'po', 't', 'wh'], ['ic', 'h', 'wa', 's', 'cr', 'e'],
                            ['a', 'te', 'd', 'fo', 'r', 'th'], ['eb', 'l', 'is', 's', 'of', 's'],
                            ['o', 'ul', 's', 'li', 'k', 'em'], ['in', 'e', 'ia', 'm', 'so', 'h'],
                            ['a', 'pp', 'y', 'my', 'd', 'ea'], ['rf', 'r', 'ie', 'n', 'ds', 'o'],
                            ['a', 'bs', 'o', 'rb', 'e', 'di'], ['nt', 'h', 'ee', 'x', 'qu', 'i'],
                            ['s', 'it', 'e', 'se', 'n', 'se'], ['of', 'm', 'er', 'e', 'tr', 'a'],
                            ['n', 'qu', 'i', 'le', 'x', 'is'], ['te', 'n', 'ce', 't', 'ha', 't'],
                            ['i', 'ne', 'g', 'le', 'c', 'tm'], ['yt', 'a', 'le', 'n', 'ts', 'i'],
                            ['s', 'ho', 'u', 'ld', 'b', 'ei'], ['nc', 'a', 'pa', 'b', 'le', 'o'],
                            ['f', 'dr', 'a', 'wi', 'n', 'ga'], ['si', 'n', 'gl', 'e', 'st', 'r'],
                            ['o', 'ke', 'a', 'tt', 'h', 'ep'], ['re', 's', 'en', 't', 'mo', 'm'],
                            ['e', 'nt', 'a', 'nd', 'y', 'et'], ['if', 'e', 'el', 't', 'ha', 't'],
                            ['i', 'ne', 'v', 'er', 'w', 'as'], ['ag', 'r', 'ea', 't', 'er', 'a'],
                            ['r', 'ti', 's', 'tt', 'h', 'an'], ['no', 'w', 'wh', 'e', 'nw', 'h'],
                            ['i', 'le', 't', 'he', 'l', 'ov'], ['el', 'y', 'va', 'l', 'le', 'y'],
                            ['t', 'ee', 'm', 'sw', 'i', 'th'], ['va', 'p', 'ou', 'r', 'ar', 'o'],
                            ['u', 'nd', 'm', 'ea', 'n', 'dt'], ['he', 'm', 'er', 'i', 'di', 'a'],
                            ['n', 'su', 'n', 'st', 'r', 'ik'], ['es', 't', 'he', 'u', 'pp', 'e'],
                            ['r', 'su', 'r', 'fa', 'c', 'eo'], ['ft', 'h', 'ei', 'm', 'pe', 'n'],
                            ['e', 'tr', 'a', 'bl', 'e', 'fo'], ['li', 'a', 'ge', 'o', 'fm', 'y'],
                            ['t', 're', 'e', 'sa', 'n', 'db'], ['ut', 'a', 'fe', 'w', 'st', 'r'],
                            ['a', 'yg', 'l', 'ea', 'm', 'ss'], ['te', 'a', 'li', 'n', 'to', 't'],
                            ['h', 'ei', 'n', 'ne', 'r', 'sa'], ['nc', 't', 'ua', 'r', 'y']]
        },
    ]
}
